### ISSUE TITLE
Unable to load library 'jeigen-linux-64': Can't obtain InputStream for linux-x86-64/libjeigen-linux-64.so

### ISSUE THREAD

**Issue by wuyunqiq** [hughperkins/jeigen#17]
When I run the "Sanity testing build" on linux by:
java -cp build/linux-64/Jeigen-linux-64.jar:build/linux-64/jna-4.1.0.jar jeigen.TestSimple

I meet a problem shown as follows:
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'jeigen-linux-64': Can't obtain InputStream for linux-x86-64/libjeigen-linux-64.so
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Native.register(Native.java:1396)
	at com.sun.jna.Native.register(Native.java:1156)
	at jeigen.JeigenJna$Jeigen.<clinit>(JeigenJna.java:64)
	at jeigen.DenseMatrix.mmul(DenseMatrix.java:1049)
	at jeigen.TestSimple.main(TestSimple.java:14)

How to solve this problem?

**Comment by pohebeyy** [comment]
did you solve the problem?
